# Generated by Django 4.1.7 on 2023-04-18 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('rating', models.FloatField(blank=True, default=0)),
                ('available_start', models.DateField(default=None)),
                ('available_end', models.DateField(default=None)),
                ('amenities', models.CharField(blank=True, max_length=500, null=True)),
                ('image_cover', models.ImageField(upload_to='property')),
                ('num_guest', models.IntegerField()),
                ('description', models.TextField(default='No descriptions available')),
                ('price', models.FloatField()),
                ('num_bed', models.IntegerField()),
                ('num_bath', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='property')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property')),
            ],
        ),
    ]
